rules:
  - pattern: "java.lang:type=Memory"
    name: "jvm_memory_used_bytes"
    type: GAUGE
    help: "Used JVM Heap Memory"
    labels:
      area: "heap"
    attr:
      HeapMemoryUsage:
        used: "used"

  - pattern: "java.lang:type=Memory"
    name: "jvm_memory_committed_bytes"
    type: GAUGE
    help: "Committed JVM Heap Memory"
    labels:
      area: "heap"
    attr:
      HeapMemoryUsage:
        committed: "committed"

  - pattern: "java.lang:type=Memory"
    name: "jvm_memory_max_bytes"
    type: GAUGE
    help: "Max JVM Heap Memory"
    labels:
      area: "heap"
    attr:
      HeapMemoryUsage:
        max: "max"
