rules:
  - pattern: ".*"
    name: "jvm_memory_used_bytes"
    type: GAUGE
    help: "Used JVM Heap Memory"
    labels:
      area: "heap"
      type: "used"
    attr: "Used"
  - pattern: ".*"
    name: "jvm_memory_committed_bytes"
    type: GAUGE
    help: "Committed JVM Heap Memory"
    labels:
      area: "heap"
      type: "committed"
    attr: "Committed"
  - pattern: ".*"
    name: "jvm_memory_max_bytes"
    type: GAUGE
    help: "Max JVM Heap Memory"
    labels:
      area: "heap"
      type: "max"
    attr: "Max"
